import { Hospital, Doctor } from './types';

// Mock dataset representing the data.gov.in / ABDM HFR fallback data
// Coordinates roughly around New Delhi (Connaught Place: 28.6304, 77.2177)
export const MOCK_HOSPITALS: Hospital[] = [
  {
    id: 'hfr-001',
    name: 'Safdarjung Hospital',
    type: 'Government',
    address: 'Ansari Nagar East, near AIIMS Metro Station, New Delhi',
    phone: '+91-11-26165060',
    specialties: ['Trauma', 'Cardiology', 'Neurology', 'Orthopedics'],
    services: ['CT Scan', 'Burn Ward', 'ICU', 'MRI', 'X-Ray', '24/7 Pharmacy', 'Ambulance'],
    emergencyServices: true,
    bedsAvailable: 42,
    bloodBank: true,
    lat: 28.5682,
    lng: 77.2069,
  },
  {
    id: 'hfr-002',
    name: 'All India Institute of Medical Sciences (AIIMS)',
    type: 'Government',
    address: 'Sri Aurobindo Marg, Ansari Nagar, New Delhi',
    phone: '+91-11-26588500',
    specialties: ['Multispecialty', 'Trauma', 'Oncology', 'Cardiothoracic'],
    services: ['CT Scan', 'ICU', 'MRI', 'X-Ray', '24/7 Pharmacy', 'Ambulance', 'Robotic Surgery', 'Dialysis'],
    emergencyServices: true,
    bedsAvailable: 15,
    bloodBank: true,
    lat: 28.5672,
    lng: 77.2100,
  },
  {
    id: 'hfr-003',
    name: 'Sir Ganga Ram Hospital',
    type: 'Trust',
    address: 'Rajinder Nagar, New Delhi',
    phone: '+91-11-25750000',
    specialties: ['Cardiology', 'Gastroenterology', 'Neurology'],
    services: ['CT Scan', 'ICU', 'MRI', 'Dialysis', '24/7 Pharmacy'],
    emergencyServices: true,
    bedsAvailable: 8,
    bloodBank: true,
    lat: 28.6385,
    lng: 77.1895,
  },
  {
    id: 'hfr-004',
    name: 'Dr. Ram Manohar Lohia Hospital',
    type: 'Government',
    address: 'Baba Kharak Singh Marg, New Delhi',
    phone: '+91-11-23365525',
    specialties: ['Trauma', 'Burn Ward', 'General Surgery'],
    services: ['CT Scan', 'Burn Ward', 'ICU', 'X-Ray', 'Ambulance'],
    emergencyServices: true,
    bedsAvailable: 64,
    bloodBank: true,
    lat: 28.6253,
    lng: 77.2001,
  },
  {
    id: 'hfr-005',
    name: 'Fortis Escorts Heart Institute',
    type: 'Private',
    address: 'Okhla Road, New Friends Colony, New Delhi',
    phone: '+91-11-47135000',
    specialties: ['Cardiology', 'Cardiac Surgery'],
    services: ['CT Scan', 'ICU', 'MRI', '24/7 Pharmacy'],
    emergencyServices: true,
    bedsAvailable: 3,
    bloodBank: false,
    lat: 28.5615,
    lng: 77.2731,
  },
  {
    id: 'hfr-006',
    name: 'Lok Nayak Jai Prakash Narayan Hospital',
    type: 'Government',
    address: 'Jawaharlal Nehru Marg, New Delhi',
    phone: '+91-11-23236000',
    specialties: ['Trauma', 'Pediatrics', 'Orthopedics'],
    services: ['CT Scan', 'Burn Ward', 'ICU', 'X-Ray', 'Ambulance', 'Neonatal ICU'],
    emergencyServices: true,
    bedsAvailable: 112,
    bloodBank: true,
    lat: 28.6378,
    lng: 77.2405,
  },
  {
    id: 'hfr-007',
    name: 'Indraprastha Apollo Hospitals',
    type: 'Private',
    address: 'Sarita Vihar, Delhi Mathura Road, New Delhi',
    phone: '+91-11-26925858',
    specialties: ['Multispecialty', 'Organ Transplant', 'Oncology'],
    services: ['CT Scan', 'ICU', 'MRI', 'Robotic Surgery', '24/7 Pharmacy', 'Ambulance'],
    emergencyServices: true,
    bedsAvailable: 24,
    bloodBank: true,
    lat: 28.5398,
    lng: 77.2845,
  },
  {
    id: 'hfr-008',
    name: 'Max Super Speciality Hospital',
    type: 'Private',
    address: 'Press Enclave Road, Saket, New Delhi',
    phone: '+91-11-26515050',
    specialties: ['Cardiology', 'Neurology', 'Orthopedics'],
    services: ['CT Scan', 'ICU', 'MRI', 'X-Ray', 'Dialysis', '24/7 Pharmacy'],
    emergencyServices: true,
    bedsAvailable: 12,
    bloodBank: true,
    lat: 28.5273,
    lng: 77.2120,
  },
  {
    id: 'hfr-009',
    name: 'BLK-Max Super Speciality Hospital',
    type: 'Private',
    address: 'Pusa Road, Radha Soami Satsang, New Delhi',
    phone: '+91-11-30403040',
    specialties: ['Oncology', 'Bone Marrow Transplant', 'Gastroenterology'],
    services: ['CT Scan', 'ICU', 'MRI', 'X-Ray', 'Ambulance', 'Blood Bank'],
    emergencyServices: true,
    bedsAvailable: 18,
    bloodBank: true,
    lat: 28.6425,
    lng: 77.1824,
  },
  {
    id: 'hfr-010',
    name: 'Holy Family Hospital',
    type: 'Trust',
    address: 'Okhla Road, New Delhi',
    phone: '+91-11-26845900',
    specialties: ['General Medicine', 'Pediatrics', 'Obstetrics'],
    services: ['ICU', 'X-Ray', '24/7 Pharmacy', 'Ambulance'],
    emergencyServices: true,
    bedsAvailable: 35,
    bloodBank: true,
    lat: 28.5613,
    lng: 77.2750,
  }
];

export const MOCK_BLOOD_BANKS = [
  {
    id: 'bb-001',
    name: 'Indian Red Cross Society Blood Bank',
    address: '1, Red Cross Road, New Delhi',
    lat: 28.6212,
    lng: 77.2045,
    stock: { 'O+': 145, 'O-': 12, 'A+': 89, 'A-': 5, 'B+': 112, 'B-': 8, 'AB+': 45, 'AB-': 2 },
    lastUpdated: '5 mins ago'
  },
  {
    id: 'bb-002',
    name: 'AIIMS Main Blood Bank',
    address: 'Sri Aurobindo Marg, New Delhi',
    lat: 28.5672,
    lng: 77.2100,
    stock: { 'O+': 45, 'O-': 2, 'A+': 30, 'A-': 0, 'B+': 55, 'B-': 1, 'AB+': 8, 'AB-': 0 },
    lastUpdated: '12 mins ago'
  },
  {
    id: 'bb-003',
    name: 'Rotary Blood Bank',
    address: 'Tughlakabad Institutional Area, New Delhi',
    lat: 28.5134,
    lng: 77.2612,
    stock: { 'O+': 0, 'O-': 0, 'A+': 12, 'A-': 2, 'B+': 34, 'B-': 4, 'AB+': 15, 'AB-': 1 },
    lastUpdated: '1 hour ago'
  },
  {
    id: 'bb-004',
    name: 'Lions Blood Bank',
    address: 'Shalimar Bagh, New Delhi',
    lat: 28.7180,
    lng: 77.1610,
    stock: { 'O+': 55, 'O-': 4, 'A+': 28, 'A-': 1, 'B+': 42, 'B-': 2, 'AB+': 10, 'AB-': 0 },
    lastUpdated: '15 mins ago'
  },
  {
    id: 'bb-005',
    name: 'Armed Forces Transfusion Centre',
    address: 'Delhi Cantt, New Delhi',
    lat: 28.5960,
    lng: 77.1350,
    stock: { 'O+': 250, 'O-': 30, 'A+': 140, 'A-': 15, 'B+': 180, 'B-': 20, 'AB+': 75, 'AB-': 10 },
    lastUpdated: '2 mins ago'
  },
  {
    id: 'bb-006',
    name: 'Sir Ganga Ram Hospital Blood Bank',
    address: 'Rajinder Nagar, New Delhi',
    lat: 28.6385,
    lng: 77.1895,
    stock: { 'O+': 18, 'O-': 1, 'A+': 4, 'A-': 0, 'B+': 22, 'B-': 0, 'AB+': 3, 'AB-': 0 },
    lastUpdated: '34 mins ago'
  }
];

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: 'doc-001',
    name: 'Dr. Vikram Singh',
    specialty: 'Cardiologist',
    experience: 15,
    qualification: 'MBBS, MD - Cardiology',
    clinic: 'Heart Care Clinic',
    address: 'Connaught Place, New Delhi',
    fee: 1500,
    rating: 4.8,
    availableNext: 'Today, 4:00 PM',
    lat: 28.6304,
    lng: 77.2177,
  },
  {
    id: 'doc-002',
    name: 'Dr. Sneha Rao',
    specialty: 'Dermatologist',
    experience: 8,
    qualification: 'MBBS, DDVL',
    clinic: 'Skin Glow Clinic',
    address: 'Rajinder Nagar, New Delhi',
    fee: 800,
    rating: 4.5,
    availableNext: 'Tomorrow, 10:00 AM',
    lat: 28.6385,
    lng: 77.1895,
  },
  {
    id: 'doc-003',
    name: 'Dr. Aarti Sharma',
    specialty: 'Pediatrician',
    experience: 12,
    qualification: 'MBBS, MD - Pediatrics',
    clinic: 'Little Smiles Care',
    address: 'Green Park, New Delhi',
    fee: 1000,
    rating: 4.9,
    availableNext: 'Today, 2:30 PM',
    lat: 28.5562,
    lng: 77.2065,
  },
  {
    id: 'doc-004',
    name: 'Dr. Rahul Verma',
    specialty: 'Orthopedic',
    experience: 20,
    qualification: 'MBBS, MS - Orthopedics',
    clinic: 'Bone & Joint Centre',
    address: 'Vasant Kunj, New Delhi',
    fee: 1200,
    rating: 4.7,
    availableNext: 'Tomorrow, 5:00 PM',
    lat: 28.5293,
    lng: 77.1534,
  },
  {
    id: 'doc-005',
    name: 'Dr. Priya Patel',
    specialty: 'Gynecologist',
    experience: 10,
    qualification: 'MBBS, MD - Obstetrics & Gynecology',
    clinic: 'Women Wellness Clinic',
    address: 'Lajpat Nagar, New Delhi',
    fee: 1000,
    rating: 4.8,
    availableNext: 'Today, 6:00 PM',
    lat: 28.5678,
    lng: 77.2433,
  },
  {
    id: 'doc-006',
    name: 'Dr. Amit Singh',
    specialty: 'General Physician',
    experience: 5,
    qualification: 'MBBS',
    clinic: 'City Health Clinic',
    address: 'Karol Bagh, New Delhi',
    fee: 500,
    rating: 4.4,
    availableNext: 'Today, 1:00 PM',
    lat: 28.6538,
    lng: 77.1906,
  }
];

